// Reference data for one general election, generated by `pnpm data:build`
// from the Ministerio del Interior's Infoelectoral results.
export type Election = {
  // Year and month of the election, e.g. "2023-07".
  id: string;
  date: string;
  // Every list that ran somewhere; results point to it by id (R-08).
  candidacies: ElectionCandidacy[];
  constituencies: ElectionConstituency[];
};

export type ElectionCandidacy = {
  id: string;
  acronym: string;
  name: string;
};

export type ElectionConstituency = {
  // INE province code; 51 and 52 are Ceuta and Melilla.
  code: string;
  name: string;
  seats: number;
  population: number;
  census: number;
  blankVotes: number;
  nullVotes: number;
  results: CandidacyVotes[];
};

export type CandidacyVotes = {
  candidacyId: string;
  votes: number;
  // Official seats won, kept to check the engine against the real count.
  elected: number;
};

// National grouping of local candidacies (R-08); every election ships a
// default set the user can edit (FR-11).
export type Bloc = {
  id: string;
  name: string;
  colour: string;
  candidacyIds: string[];
};
